drivers/__init__.py
from flask import Blueprint

drivers = Blueprint('drivers', __name__, template_folder='templates')

from . import views

drivers/views.py
from flask import render_template, request, session, jsonify, g
import folium
from flask_login import login_required, current_user
from dotenv import load_dotenv
import os
from pymongo import MongoClient
from bson import ObjectId
import sqlite3

from . import drivers

load_dotenv()

# Connect to MongoDB database
db = MongoClient(os.getenv('MONGO_URI'))['uber']
active_orders = db['active_orders']

# Set default location from environment variables
default_location = [os.getenv('DEFAULT_LAT'), os.getenv('DEFAULT_LNG')]

def get_db():
    """
    Connect to SQLite database and return the connection.
    """
    db = getattr(g, '_database', None)
    if db is None:
        db = g._database = sqlite3.connect('uber_application.db')
    return db

@drivers.route('/driver_home')
@login_required
def driver_home():
    """
    Render the driver home page with a map and pending orders.
    """
    db = get_db()
    cursor = db.cursor()
    cursor.execute('SELECT vehicle FROM drivers WHERE id=?', (current_user.id,))
    vehicle_type = cursor.fetchone()[0]

    driver_location = session.get('driver_location', None)
    if not driver_location:
        sent_location = False
        driver_location = default_location
    else:
        sent_location = True

    # Create a map centered at driver's location
    map = folium.Map(location=driver_location, zoom_start=15)

    # Find pending orders for the driver's vehicle type
    pending_orders = active_orders.find({'status': 'waiting', 'vehicle_type': vehicle_type})

    num_orders = 0
    for order in pending_orders:
        num_orders += 1
        origin = order['origin']
        destination = order['destination']
        distance = order['distance']
        price = order['price']
        id = str(order['_id'])

        # Create a marker to display the order details on the map
        order_marker_html = f"""
            <form action="javascript:;" onsubmit="parent.acceptOrder(\'{id}\')">
                <input type='hidden' name='order_id' value='{id}'>
                <strong>Pickup location: </strong>{origin[0]}, {origin[1]}<br>
                <strong>Destination: </strong>{destination[0]}, {destination[1]}<br>
                <strong>Distance: </strong>{round(distance,2)}<br>
                <strong>Price: </strong>{round(price,2)}<br>
                <input type="submit" value="Accept">
            </form>"""
        marker = folium.Marker(origin, popup=order_marker_html, tooltip='<strong>Awaiting order</strong>', icon=folium.Icon(color='green', icon='car', prefix='fa'))
        marker.add_to(map)

    # Add a marker for the driver's location
    folium.Marker(driver_location, tooltip=f'<strong>Your location</strong><br>{driver_location[0]},{driver_location[1]}').add_to(map)

    return render_template('driver_home.html', map=map._repr_html_(), sent_location=sent_location, default_location=default_location, driver_name=current_user.username, num_orders=num_orders)

@drivers.route('/receive_driver_location', methods=['POST'])
def receive_driver_location():
    """
    Receive and store the driver's location from a POST request.
    """
    location = request.get_json()['location']
    session['driver_location'] = [location['lat'], location['lng']]
    return jsonify({'result': 'success'})

@drivers.route('/accept_order', methods=['POST'])
def accept_order():
    """
    Accept an order from a POST request.
    """
    str_id = request.json.get('order_id')
    obj_id = ObjectId(str_id)
    active_orders.update_one({'_id': obj_id}, {'$set': {
        'driver': current_user.id,
        'driver_name': current_user.username,
        'status': 'accepted',
    }})
    return jsonify({'result': 'success'})

@drivers.route('/driver_ongoing_ride/<order_id>')
@login_required
def driver_ongoing_ride(order_id):
    """
    Render the page for an ongoing ride.
    """
    obj_id = ObjectId(order_id)
    order = active_orders.find_one({'_id': obj_id})
    client_name = order['client_name']
    origin = order['origin']
    destination = order['destination']
    distance = order['distance']
    return render_template('driver_ongoing_ride.html', client_name=client_name, origin=origin, destination=destination, distance=distance, driver_name = current_user.username, order_id=order_id)

@drivers.route('/end_ride', methods=['POST'])
def end_ride():
    """
    End a ride from a POST request.
    """
    str_id = request.get_json()['order_id']
    completion_time = request.get_json()['time']
    obj_id = ObjectId(str_id)
    active_orders.update_one({'_id': obj_id}, {'$set': {
        'status': 'completed',
        'completed_at': completion_time
    }})
    print(f'Order {str_id} completed')
    return jsonify({'result': 'success'})

@drivers.route('/ride_summary/<str_order_id>')
@login_required
def ride_summary(str_order_id):
    """
    Render the summary of a completed ride.
    """
    obj_id = ObjectId(str_order_id)
    order = active_orders.find_one({'_id': obj_id})
    client_name = order['client_name']
    vehicle = order['vehicle_type']
    origin = order['origin']
    destination = order['destination']
    distance = round(order['distance'], 2)
    departure_time = order['departure_time']
    completed_at = order['completed_at']
    price = round(order['price'], 2)
    return render_template('ride_summary.html', client_name=client_name, origin=origin, destination=destination, distance=distance, price=price, driver_name=current_user.username, vehicle=vehicle, departure_time=departure_time, completed_at=completed_at)

drivers/templates/driver_home.html
<!DOCTYPE html>
<html>
    <head>
        <title>Driver Home Page</title>
        <meta charset="utf-8">
        <!-- Leaflet CSS -->
        <link rel="stylesheet" href="https://unpkg.com/leaflet/dist/leaflet.css" />
        <!--jquery-->
        <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.1.0/jquery.min.js"></script>
        <!-- Bootstrap -->
        <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-T3c6CoIi6uLrA9TneNEoa7RxnatzjcDSCmG1MXxSR1GAsXEV/Dwwykc2MPK8M2HN" crossorigin="anonymous">
    </head>
    <script>
        function fetchLocation() {
            // Try HTML5 geolocation.
            if (navigator.geolocation) {
                navigator.geolocation.getCurrentPosition(function (position) {
                    var pos = {
                        lat: position.coords.latitude,
                        lng: position.coords.longitude
                    };
                    sendLocation(pos.lat, pos.lng);
                }, function () {
                    handleLocationError(true);
                });
            } else {
                // Browser doesn't support Geolocation
                handleLocationError(false);
            }
        };
        
        function handleLocationError(browserHasGeolocation) {
            if (browserHasGeolocation) {
                console.log("The Geolocation service failed.");
            } else {
                console.log("Browser doesn't support geolocation.");
            }
            var pos = {
                lat: parseFloat("{{ default_location[0] }}"),
                lng: parseFloat("{{ default_location[1] }}")
            };
            console.log("Using default position: " + pos);
            sendLocation(pos.lat, pos.lng);
        };

        function sendLocation(lat, lng) {
            console.log("Sending location: " + lat + ", " + lng);
            $.ajax({
                type: "POST",
                url: "{{ url_for('drivers.receive_driver_location') }}",
                contentType: "application/json",
                data: JSON.stringify({ location: { lat: lat, lng: lng } }),
                dataType: "json",
                success: function (response) {
                    console.log(response);
                    location.reload();
                },
                error: function (err) {
                    console.log(err);
                }
            });
        };

    function acceptOrder(order_id) {
        console.log("Accepting order: " + order_id);
        $.ajax({
            type: "POST",
            url: "/accept_order",
            contentType: "application/json",
            data: JSON.stringify({ order_id: order_id }),
            dataType: "json",
            success: function (response) {
                console.log(response);
                window.location.href = "/driver_ongoing_ride/" + order_id;
            },
            error: function (err) {
                console.log(err);
            }
        });
};

    </script>
 <body>
    <nav class="navbar navbar-expand-lg navbar-light bg-light">
        <div class="container-fluid">
            <a class="navbar-brand" href="{{ url_for('drivers.driver_home') }}">Driver Home</a>
            <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNavAltMarkup"
             aria-controls="navbarNavAltMarkup" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
             </button>
            <div class="collapse navbar-collapse" id="navbarNavAltMarkup">
                <div class="navbar-nav">
                    <a class="nav-link" aria-current="page" href="{{ url_for('drivers.driver_home') }}">Home</a>
                    <a class="nav-link" href="{{ url_for('authentication.logout') }}">Logout</a>
                </div>
            </div>
        </div>
    </nav>
    <div class="d-flex justify-content-center align-items-center vh-100">
        <div class="container mt-3 justify-content-center">
            <h2>Welcome {{ driver_name }},</h2>
            <h3>There are {{ num_orders }} available orders</h3>
            {% if not sent_location %}
                <script>
                fetchLocation();
                </script>
            {% endif %}
        </div>
        <div class="container mt-3">
            <div id="map" style="width: 100%; max-width: 800px;">
                {{ map|safe}}
            </div>
        </div>
    </div>
</body>
</html>

drivers/templates/driver_ongoing_ride.html
<!DOCTYPE html>
<html>
    <head>
        <title>Ongoing Ride</title>
        <meta charset="utf-8">
        <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-T3c6CoIi6uLrA9TneNEoa7RxnatzjcDSCmG1MXxSR1GAsXEV/Dwwykc2MPK8M2HN" crossorigin="anonymous">
        <script src="https://code.jquery.com/jquery-3.6.0.min.js"></script>
        <script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/socket.io/4.7.2/socket.io.js"></script>
        <script type="text/javascript">
            $(document).ready(function(){
                const socket = io('http://' + document.domain + ':' + location.port + '/ride_chat');
                socket.on('connect', function(){
                    console.log("Connected to server");
                    socket.emit('join', {'room_id': '{{ order_id }}'});
                });
                socket.on('receive_message', function(data){
                    console.log(data);
                    updateChat(data.message);
                });

                socket.on('ride_ended', function(data){
                    console.log("Ride ended");
                    socket.disconnect();
                    window.location.href = "{{ url_for('drivers.ride_summary', str_order_id=order_id) }}";
                });
                function updateChat(message) {
                    $('#chat').append("<li>" + message + "</li>");
                }
                $('#send').click(function(){
                    var message = '{{ driver_name }}: ' +  $('#message').val();
                    socket.emit('send_message', {'message': message, "room_id": "{{ order_id }}"});
                    $('#message').val('');
                });

                $('#end_ride').click(function(){
                    console.log("Ending ride");
                    var time = new Date();
                    time = time.getHours() + ":" + time.getMinutes()
                    $.ajax({
                        type: "POST",
                        url: "{{ url_for('drivers.end_ride') }}",
                        contentType: "application/json",
                        data: JSON.stringify({'order_id': '{{ order_id }}', 'time': time}),
                        dataType: "json",
                        success: function (response) {
                            console.log(response);
                            socket.emit('ride_end', {'room_id': '{{ order_id }}'})
                        },
                        error: function (err) {
                            console.log(err);
                        }
                    });
                });
            });

        </script>

    </head>
    <body>
        <div class="container mt-5">
            <h1>Ongoing Ride</h1>
            <h2>Client Name: {{ client_name }}</h2>
            <h2>Origin: {{ origin }}</h2>
            <h2>Destination: {{ destination }}</h2>
            <h2>Total Distance: {{ distance }}</h2>
            <h2>Driver: {{ driver_name }}</h2>
            <div class="form-group mt-3">
                <button id="end_ride" class="btn btn-outline-info">End Ride</button>
            </div>
        </div>
    
        <div class="container mt-5">
            <h1>Chat</h1>
            <ul id="chat" class="list-group">
            </ul>
            <div class="input-group mt-3">
                <input type="text" id="message" class="form-control" placeholder="Type your message">
                <button id="send" class="btn btn-outline-info">Send</button>
            </div>
        </div>
    </body>
</html>

drivers/templates/ride_summary.html
<p>test</p>